zend_extension=/home/shusuke/.local/share/mise/installs/php/8.5.6/lib/php/extensions/no-debug-non-zts-20250925/xdebug.so

xdebug.mode=debug
xdebug.start_with_request=yes

; VSCode に接続する設定
xdebug.client_host=localhost
xdebug.client_port=9003

; ログ（必要なら）
xdebug.log=/tmp/xdebug.log
xdebug.log_level=7

